### ISSUE TITLE
Issue on Build

### ISSUE THREAD

**Issue by No9** [Osthanes/utilities#119] opened 2016-06-17 15:08 UTC
I am following this article https://developer.ibm.com/integration/blog/2015/12/15/using-containers-service-run-ibm-integration-bus-bluemix/ 
And executing it on UK Bluemix public 

And when I run the initial build step it looks like the checkout and run of this repository is failing due to what looks like an outdated tgz in the repository: https://github.com/Osthanes/utilities/blob/master/cfic826.tgz
Indicated by this line.
`You are using version 0.8.826 of the IBM Containers plug-in. Version 0.8.889 of the plug-in is available for you to install. Run the 'cf ic update'`

I am probably missing something but I don't see where I can change this in the bluemix steps so can you update the CLI in this project or perhaps there is a work around? 

```
Cloning the 'master' branch from repo 'https://github.com/No9/iib-docker.git'
Target: https://api.eu-gb.bluemix.net
git clone https://github.com/Osthanes/utilities.git utilities
Cloning into 'utilities'...
2016-06-17 14:43:32 UTC : Adjusting timestamps for files to allow cached layers
2016-06-17 14:43:32 UTC : 11 files processed in 0m 0s
2016-06-17 14:43:32 UTC : Timestamps adjusted
2016-06-17 14:43:34 UTC : APPLICATION_VERSION: 2
2016-06-17 14:43:35 UTC : Archiving to /tmp/extension_archive
2016-06-17 14:43:35 UTC : Existing Cloud Foundry CLI /opt/IBM/cf/bin/cf version 6.14.0-IDS+2654a47-2015-12-07
2016-06-17 14:43:35 UTC : Installing Cloud Foundry CLI
2016-06-17 14:43:36 UTC : Successfully installed Cloud Foundry CLI cf version 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00
2016-06-17 14:43:36 UTC : Installing IBM Container Service CLI
Installing Python 2.7
Python 2.7.6
2016-06-17 14:44:16 UTC : Successfully installed IBM Container Service CLI
2016-06-17 14:44:34 UTC : Successfully installed Docker version 1.6.2, build 7c8fca2
/tmp/extension_content ~/e5982a65-31b1-4024-9814-035a40eb072c
2016-06-17 14:44:34 UTC : New EXT_DIR/cf version: /tmp/extension_content/cf version 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00
~/e5982a65-31b1-4024-9814-035a40eb072c
"/tmp/extension_content/cf ic init" did not return successfully. RC=1. Sleep 20 sec and try again.
"/tmp/extension_content/cf ic init" did not return successfully. RC=1. Sleep 20 sec and try again.
"/tmp/extension_content/cf ic init" did not return successfully. RC=1. Sleep 20 sec and try again.
"/tmp/extension_content/cf ic init" did not return successfully. RC=1. Sleep 20 sec and try again.
"/tmp/extension_content/cf ic init" did not return successfully. RC=1. Sleep 20 sec and try again.
2016-06-17 14:46:20 UTC : 'cf ic init' command failed with return code 1
2016-06-17 14:46:20 UTC : Additional message was 'You are using version 0.8.826 of the IBM Containers plug-in. Version 0.8.889 of the plug-in is available for you to install. Run the 'cf ic update' command to update your plug-in to the current version. You can review the documentation to see the changes that are included in the new version. https://www.ng.bluemix.net/docs/containers/container_cli_reference_cfic_versions.html Deleting the old configuration file... Retrieving client certificates from IBM Containers... FAILED The namespace must be set. Run 'cf ic namespace set NAMESPACE' to set the namespace.'
We are sorry you are having trouble. 
There were 2 errors recorded during execution:
2016-06-17 14:46:20 UTC : 'cf ic init' command failed with return code 1
2016-06-17 14:46:20 UTC : Additional message was 'You are using version 0.8.826 of the IBM Containers plug-in. Version 0.8.889 of the plug-in is available for you to install. Run the 'cf ic update' command to update your plug-in to the current version. You can review the documentation to see the changes that are included in the new version. https://www.ng.bluemix.net/docs/containers/container_cli_reference_cfic_versions.html Deleting the old configuration file... Retrieving client certificates from IBM Containers... FAILED The namespace must be set. Run 'cf ic namespace set NAMESPACE' to set the namespace.'
There are a number of ways that you can get help:
1. Post a question on  https://developer.ibm.com/answers/  and 'Ask a question' with tags 'docker', 'containers' and 'devops-services'
2. Open a Work Item in our public devops project:  https://hub.jazz.net/project/alchemy/Alchemy-Ostanes 

You can also review and fork our sample scripts on  https://github.com/Osthanes 
To send notifications, set SLACK_WEBHOOK_PATH or HIP_CHAT_TOKEN in the environment

Finished: FAILED
```

**Comment by nfritze** [comment] 2016-06-17 15:23
The checkout is working, but the execution is failing when it's trying to initialize the connection to the ic service (the cf ic init).  This is on an old version of cf ic due to limitations of the pipeline execution authentication for now - the message is annoying, but not the root cause.  Could you please re-execute that stage with the env var DEBUG=1 set on that run?  It'll add some more output to help point to what's actually preventing it from connecting.

**Comment by No9** [comment] 2016-06-17 16:27
Thanks for the quick feedback 
In the mean time I went through these steps https://developer.ibm.com/integration/docs/ibm-integration-bus/using-the-containers-service-to-run-ibm-integration-bus-in-bluemix-in-10-easy-steps/ 

Part of the steps above makes you add an NAMESPACE 

Totally guessing but I think that is why this failure happened as now the original failure from DevOps is not happening an I get a successful build.

If you agree then please feel free to close this issue and thanks again

**Comment by nfritze** [comment] 2016-06-17 16:36
Ah - that makes sense.  I bet the "you don't have a namespace, please set it!" error message is being masked by the "outdated version" message.  Going to leave the issue open a bit until I get a chance to investigate that.  Thanks, and glad it's working for you now!

**Comment by nfritze** [comment] 2016-07-29 14:48
Fixed by PR https://github.com/Osthanes/utilities/pull/121

**Closed as completed by nfritze** 2016-07-29 14:48 UTC
